# Generated by Django 4.1.1 on 2022-09-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('PUBLISH', 'PUBLISH'), ('PENDING', 'PENDING')], default='PENDING', max_length=15)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
